Repository swarajmhatre/swarajmhatre_portfolio, pull requests merged in 2023-10, with the labels that each got.

#10 feat(contact): Enhanced UI and added validations
  src/components/Contact/contact.js
  src/components/Navbar/navbar.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#13 added index.css
  package-lock.json
  public/index.html
  src/index.css
  src/index.js
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#15 hover add in work,project with intro image adjust
  src/components/Intro/intro.css
  src/components/Intro/intro.js
  src/components/Skills/skills.css
  src/components/Works/works.css
Labels: hacktoberfest, hacktoberfest-accepted
